<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Welcome - <?= $$controller_name ?></title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link 
    href="/css/bootstrap/bootstrap.min.css" 
    rel="stylesheet" 
    >
</head>
<body class="bg-light d-flex align-items-center justify-content-center min-vh-100">

  <div class="card shadow-sm text-center w-100" style="max-width: 600px;">
    <div class="card-body p-4">
      <div class="display-4 mb-3">🚀</div>
      <h1 class="h4 mb-3">Hello from <strong><?= $$controller_name ?></strong> Controller</h1>
      <p class="text-muted">This page was generated by the <strong>AGAI</strong> framework.</p>
      <hr>
      <div class="text-start">
        <h6 class="fw-semibold">What's this?</h6>
        <p>
          This default view appears because a controller named 
          <code><?= $$controller_name ?></code> was detected but no custom view was found.
        </p>

        <h6 class="fw-semibold">Next steps:</h6>
        <ul class="mb-3">
          <li>Create a view at <code>views/<?= strtolower($$controller_name) ?>/index.php</code></li>
          <li>Edit logic in <code>controllers/<?= $$controller_name ?>.go</code></li>
          <li>Define routes if needed in your router or CLI tool</li>
        </ul>
      </div>
      <a href="/" class="btn btn-primary">Back to Home</a>
    </div>
  </div>

  <script 
    src="/js/bootstrap/bootstrap.bundle.min.js"></script>
</body>
</html>
